# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://siskin.im
title: Siskin IM by Tigase, Inc.
email: support@tigase.net
author: Tigase, Inc.
description: 'Lightweight and powerful XMPP client for iPhone and iPad, with audio and video calls and built-in privacy'
copyright: 'Copyright &copy; 2020 Tigase, Inc. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'
logo: img/siskin-logo.png

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title:
    superclass: b
    class: twitter
    url: https://twitter.com/tigase
  - title:
    superclass: b
    class: facebook
    url: https://www.facebook.com/tigase/
  - title:
    superclass: b
    class: mastodon
    url: https://fosstodon.org/@tigase
  - title: github
    superclass: b
    class: github
    url: https://github.com/tigase/siskin-im
